Repository shipshapecode/shepherd, pull requests merged in 2018-10, with the labels that each got.

#265 Implement `Tour.hide`
  src/js/step.js
  src/js/tour.js
  test/unit/test.tour.js
Labels: enhancement

#271 Constrain input for `Step.options.buttons` to an array of buttons.
  docs/welcome/css/welcome.css
  index.md
  package.json
  src/js/step.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/default-buttons.js
  test/unit/test.step.js
Labels: enhancement

#272 fix docs typo
  index.md
Labels: documentation

#279 Allow exit animations to play before step tooltip disappears.
  src/js/bind.js
  src/js/step.js
  src/js/tour.js
  src/js/utils/tooltip-defaults.js
  test/cypress/integration/element-targeting.spec.js
  test/cypress/integration/test.acceptance.js
  test/unit/test.step.js
  test/unit/test.tour.js
Labels: bug

#281 Bump a bunch of deps
  package.json
  yarn.lock
Labels: enhancement
