Repository shipshapecode/shepherd, pull requests merged in 2018-09, with the labels that each got.

#239 Syntax errors and ParentNode.prepend not supported in IE
  src/js/step.js
Labels: bug

#244 Rename `Tour.options.defaults` to `Tour.options.defaultStepOptions`.
  README.md
  docs/welcome/index.html
  docs/welcome/js/welcome.js
  index.md
  package.json
  src/js/tour.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/setup-tour.js
  test/dummy/index.html
  test/unit/test.step.js
  test/unit/test.tour.js
Labels: breaking

#242 Update theming documentation.
  .vscode/settings.json
  docs/assets/img/themes/dark.png
  docs/assets/img/themes/default.png
  docs/assets/img/themes/square-dark.png
  docs/assets/img/themes/square.png
  docs/themes.md
  docs/welcome/scss/welcome.scss
  index.md
Labels: documentation
