Repository shipshapecode/shepherd, pull requests merged in 2019-10, with the labels that each got.

#589 Adjust modal opening according to scrollParent
  src/js/components/shepherd-modal.svelte
  test/unit/components/shepherd-modal.spec.js
Labels: bug

#592 Add back tether support, remove popper
  demo/js/welcome.js
  jest.config.js
  landing/css/styles.css
  landing/css/welcome.css
  landing/js/welcome.js
  package.json
  src/js/components/shepherd-element.svelte
  src/js/evented.js
  src/js/step.js
  src/js/tour.js
  src/js/utils/general.js
  src/js/utils/popper-options.js
  test/cypress/integration/a11y.spec.js
  test/cypress/integration/destroying-elements.spec.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/default-steps.js
  test/unit/components/shepherd-element.spec.js
  test/unit/evented.spec.js
  test/unit/utils/popper-options.spec.js
  yarn.lock
Labels: breaking

#595 Handle modal opening for targets inside scrollable area
  src/js/components/shepherd-modal.svelte
  test/unit/components/shepherd-modal.spec.js
Labels: bug

#602 Allow title to specify callback
  src/js/components/shepherd-title.svelte
  src/js/step.js
  src/types/step.d.ts
  test/unit/components/shepherd-title.spec.js
Labels: enhancement

#596 Feature/buttons disabled option
  src/js/components/shepherd-button.svelte
  src/js/step.js
  src/types/step.d.ts
  test/unit/components/shepherd-button.spec.js
Labels: enhancement

#604 Add option to set aria-label on step buttons
  src/js/components/shepherd-button.svelte
  src/js/step.js
  test/unit/components/shepherd-button.spec.js
Labels: enhancement

#631 Allow passing index to `addStep`
  src/js/tour.js
  src/types/tour.d.ts
  test/unit/tour.spec.js
Labels: enhancement

#642 Add dependabot config
  .dependabot/config.yml
Labels: dependencies
