Repository shipshapecode/shepherd, pull requests merged in 2019-09, with the labels that each got.

#531 Refactor styleVariables, remove automatic calculations
  demo/css/welcome.css
  demo/js/welcome.js
  docs-src/tutorials/03-styling.md
  package.json
  src/js/components/shepherd-content/shepherd-footer/shepherd-button/styles.js
  src/js/components/shepherd-content/shepherd-footer/styles.js
  src/js/components/shepherd-content/shepherd-header/styles.js
  src/js/components/shepherd-content/shepherd-text/styles.js
  src/js/components/shepherd-content/styles.js
  src/js/components/shepherd-element/styles.js
  src/js/components/shepherd-modal/styles.js
  src/js/styles/generateStyles.js
  src/js/styles/utils.js
  src/js/styles/variables.js
  src/js/utils/tippy-popper-options.js
  yarn.lock
Labels: breaking

#532 Fix tab focus when there are no focusable elements
  src/js/components/shepherd-element/index.jsx
Labels: bug

#533 fix variable name typo
  src/js/styles/generateStyles.js
Labels: bug

#534 Remove `disableScroll` option
  docs-src/tutorials/04-cookbook.md
  docs-src/tutorials/config.json
  package.json
  src/js/tour.jsx
  src/types/tour.d.ts
  yarn.lock
Labels: breaking

#535 Remove IE11 polyfills, in favor of apps including them
  README.md
  babel.config.js
  demo/index.html
  package.json
  src/js/shepherd.js
  src/js/step.jsx
  src/js/styles/nano.js
  yarn.lock
Labels: breaking

#536 Convert from Preact to Svelte
  .eslintrc.js
  .jsdoc.js
  babel.config.js
  jest.config.js
  package.json
  rollup.config.js
  src/js/components/shepherd-content/index.jsx
  src/js/components/shepherd-content/index.svelte
  src/js/components/shepherd-content/shepherd-footer/index.jsx
  src/js/components/shepherd-content/shepherd-footer/index.svelte
  src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.jsx
  src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.svelte
  src/js/components/shepherd-content/shepherd-header/index.jsx
  src/js/components/shepherd-content/shepherd-header/index.svelte
  src/js/components/shepherd-content/shepherd-text/index.jsx
  src/js/components/shepherd-content/shepherd-text/index.svelte
  src/js/components/shepherd-element/index.jsx
  src/js/components/shepherd-element/index.svelte
  src/js/components/shepherd-modal/index.jsx
  src/js/components/shepherd-modal/index.svelte
  src/js/components/shepherd-modal/styles.js
  src/js/evented.js
  src/js/shepherd.js
  src/js/step.js
  src/js/styles/nano.js
  src/js/tour.js
  src/js/utils/modal.js
  test/.eslintrc.js
  test/unit/components/shepherd-element.spec.js
  test/unit/components/shepherd-footer.spec.js
  test/unit/components/shepherd-header.spec.js
  test/unit/components/shepherd-modal.spec.js
  test/unit/components/shepherd-text.spec.js
  test/unit/setupTests.js
  test/unit/step.spec.js
  test/unit/utils/bind.spec.js
  test/unit/utils/cleanup.spec.js
  test/unit/utils/general.spec.js
  test/unit/utils/tippy-popper-options.spec.js
  yarn.lock
Labels: enhancement

#542 Remove get-value dependency
  package.json
  src/js/step.js
  src/js/utils/tippy-popper-options.js
  yarn.lock
Labels: enhancement

#551 Remove tippy.js, add back popper.js
  .eslintrc.js
  demo/css/welcome.css
  demo/index.html
  demo/js/welcome.js
  docs-src/tutorials/02-usage.md
  jest.config.js
  package.json
  rollup.config.js
  src/js/components/shepherd-button.svelte
  src/js/components/shepherd-cancel-icon.svelte
  src/js/components/shepherd-content.svelte
  src/js/components/shepherd-element.svelte
  src/js/components/shepherd-footer.svelte
  src/js/components/shepherd-header.svelte
  src/js/components/shepherd-modal.svelte
  src/js/components/shepherd-text.svelte
  src/js/components/shepherd-title.svelte
  src/js/shepherd.js
  src/js/step.js
  src/js/tour.js
  src/js/utils/general.js
  src/js/utils/popper-options.js
  src/js/utils/tippy-popper-options.js
  src/js/utils/tooltip-defaults.js
  src/styles/global.css
  src/styles/global.scss
  src/types/step.d.ts
  src/types/tour.d.ts
  svelte.config.js
  test/cypress/integration/a11y.spec.js
  test/cypress/integration/element-targeting.spec.js
  test/cypress/integration/modal.spec.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/default-steps.js
  test/dummy/index.html
  test/unit/step.spec.js
  test/unit/tour.spec.js
  test/unit/utils/popper-options.spec.js
  test/unit/utils/tippy-popper-options.spec.js
  yarn.lock
Labels: breaking

#555 Remove classPrefix from several elements, use path for overlay
  package.json
  rollup.config.js
  src/js/components/shepherd-button.svelte
  src/js/components/shepherd-cancel-icon.svelte
  src/js/components/shepherd-content.svelte
  src/js/components/shepherd-element.svelte
  src/js/components/shepherd-footer.svelte
  src/js/components/shepherd-header.svelte
  src/js/components/shepherd-modal.svelte
  src/js/components/shepherd-text.svelte
  src/js/components/shepherd-title.svelte
  src/js/shepherd.js
  src/js/step.js
  src/js/tour.js
  src/styles/global.css
  test/cypress/integration/a11y.spec.js
  test/cypress/integration/modal.spec.js
  test/cypress/integration/test.acceptance.js
  test/unit/components/shepherd-modal.spec.js
Labels: breaking

#557 Add arrow option
  docs-src/tutorials/02-usage.md
  src/js/components/shepherd-element.svelte
  src/js/step.js
  src/js/tour.js
  src/types/step.d.ts
  test/unit/components/shepherd-element.spec.js
  test/unit/components/shepherd-footer.spec.js
  test/unit/components/shepherd-header.spec.js
  test/unit/components/shepherd-modal.spec.js
  test/unit/components/shepherd-text.spec.js
  test/unit/step.spec.js
Labels: enhancement

#560 Add tests for multiple tours
  package.json
  src/js/step.js
  src/js/tour.js
  test/.eslintrc.js
  test/cypress/integration/a11y.spec.js
  test/cypress/integration/element-targeting.spec.js
  test/cypress/integration/modal.spec.js
  test/cypress/integration/test.acceptance.js
  test/cypress/support/index.js
  test/cypress/utils/setup-tour.js
  test/unit/components/shepherd-element.spec.js
  test/unit/components/shepherd-header.spec.js
  test/unit/components/shepherd-modal.spec.js
  test/unit/setupTests.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
  test/unit/utils/bind.spec.js
  yarn.lock
Labels: enhancement

#581 Implement ability to update step options
  src/js/components/shepherd-text.svelte
  src/js/step.js
  test/unit/step.spec.js
Labels: enhancement
