Repository shipshapecode/shepherd, pull requests merged in 2019-07, with the labels that each got.

#420 Tippy v5
  docs/welcome/css/welcome.css
  package.json
  rollup.config.js
  src/js/tour.js
  src/scss/_variables.scss
  src/scss/tippy/_base-tooltips.scss
  src/scss/tippy/_popper-theme-arrows.scss
  test/cypress/integration/a11y.spec.js
  test/cypress/integration/element-targeting.spec.js
  test/cypress/integration/modal.spec.js
  test/cypress/integration/test.acceptance.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
  yarn.lock
Labels: breaking

#422 .shepherd-popper -> .shepherd, move .shepherd-has-title
  docs/welcome/css/welcome.css
  src/js/step.js
  src/js/utils/general.js
  src/scss/_base.scss
  src/scss/tippy/_base-tooltips.scss
  src/scss/tippy/_popper-theme-arrows.scss
  test/dummy/css/welcome.css
Labels: breaking

#424 Only add keydown listeners once
  src/js/step.js
Labels: bug

#429 Remove array support for `step.options.text`
  docs/welcome/js/welcome.js
  index.md
  src/js/step.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/default-steps.js
  test/unit/step.spec.js
Labels: breaking

#430 Cleanup public/private API
  src/js/step.js
  src/js/tour.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
Labels: enhancement

#434 fix for incorrect types path in package.json
  package.json
Labels: bug

#436 Remove drop util
  babel.config.js
  package.json
  src/js/evented.js
  src/js/utils/general.js
  test/unit/evented.spec.js
  test/unit/tour.spec.js
  yarn.lock
Labels: enhancement

#438 Start fixing IE11 support
  babel.config.js
  package.json
  rollup.config.js
  yarn.lock
Labels: bug

#439 Polyfill all `usage` with core-js
  babel.config.js
  package.json
  rollup.config.js
  yarn.lock
Labels: bug

#440 Use autoBind, pass context rather than manually binding
  package.json
  src/js/step.js
  src/js/tour.js
  src/js/utils/bind.js
  src/js/utils/general.js
  test/unit/step.spec.js
  test/unit/utils/bind.spec.js
  test/unit/utils/general.spec.js
  yarn.lock
Labels: breaking

#447 Import ES5 bodyScrollLock, use babel-transform-runtime
  babel.config.js
  package.json
  rollup.config.js
  src/js/modal.js
  src/js/step.js
  src/js/tour.js
  src/js/utils/auto-bind.js
  src/js/utils/bind.js
  yarn.lock
Labels: enhancement

#448 Only run release stages when tagged
  .travis.yml
Labels: invalid

#450 Switch to CSSinJS
  .stylelintrc.js
  demo/css/welcome.css
  demo/index.html
  demo/js/welcome.js
  docs-src/tutorials/03-styling.md
  docs-src/tutorials/predefined-themes.md
  package.json
  rollup.config.js
  src/js/modal.js
  src/js/shepherd.js
  src/js/step.js
  src/js/styles/generateStyles.js
  src/js/styles/nano.js
  src/js/styles/themes.js
  src/js/styles/variables.js
  src/js/tour.js
  src/js/utils/general.js
  src/scss/_base.scss
  src/scss/_functions.scss
  src/scss/_helpers.scss
  src/scss/_mixins.scss
  src/scss/_modal-overlay.scss
  src/scss/_tippy.scss
  src/scss/_variables.scss
  src/scss/helpers/_box-sizing.scss
  src/scss/mixins/_inline-block.scss
  src/scss/mixins/_pie-clearfix.scss
  src/scss/mixins/_shepherd-button.scss
  src/scss/shepherd-theme-dark.scss
  src/scss/shepherd-theme-default.scss
  src/scss/shepherd-theme-square-dark.scss
  src/scss/shepherd-theme-square.scss
  src/scss/tippy/_base-tooltips.scss
  src/scss/tippy/_popper-theme-arrows.scss
  test/dummy/css/prism.css
  test/dummy/css/welcome.css
  test/dummy/index.html
  test/unit/modal.spec.js
  test/unit/step.spec.js
  test/unit/utils/bind.spec.js
  yarn.lock
Labels: breaking

#452 Add prefix to data attributes
  src/js/step.js
  src/js/tour.js
Labels: enhancement

#453 Prefixes fixes
  demo/js/welcome.js
  src/js/step.js
  src/js/styles/generateStyles.js
  src/js/styles/nano.js
  src/js/tour.js
  src/js/utils/bind.js
  src/js/utils/general.js
Labels: enhancement

#457 Add first class support for secondary button
  demo/js/welcome.js
  docs-src/tutorials/02-usage.md
  src/js/step.js
Labels: enhancement

#462 Remove predefined themes
  docs-src/assets/img/themes/dark.png
  docs-src/assets/img/themes/default.png
  docs-src/assets/img/themes/square-dark.png
  docs-src/assets/img/themes/square.png
  docs-src/tutorials/02-usage.md
  docs-src/tutorials/03-styling.md
  docs-src/tutorials/config.json
  docs-src/tutorials/predefined-themes.md
  src/js/styles/themes.js
  src/js/styles/variables.js
Labels: breaking

#464 Simplify addStep API
  demo/index.html
  demo/js/welcome.js
  docs-src/tutorials/02-usage.md
  src/js/step.jsx
  src/js/tour.jsx
  src/types/tour.d.ts
  test/cypress/utils/default-steps.js
  test/cypress/utils/setup-tour.js
  test/dummy/index.html
  test/unit/step.spec.js
  test/unit/tour.spec.js
Labels: breaking

#465 Document canClickTarget
  docs-src/tutorials/02-usage.md
  src/js/step.jsx
Labels: documentation

#466 Switch modals from ids to classes and prefix them
  src/js/components/shepherd-modal/index.jsx
  src/js/components/shepherd-modal/styles.js
  src/js/step.jsx
  src/js/styles/generateStyles.js
  src/js/tour.jsx
  src/js/utils/modal.jsx
  test/cypress/integration/modal.spec.js
  test/unit/components/shepherd-modal.spec.js
Labels: breaking

#467 Make build smaller, while still supporting IE11
  babel.config.js
  package.json
  rollup.config.js
  src/js/shepherd.js
  src/js/styles/nano.js
  yarn.lock
Labels: enhancement

#468 switched to default export in TS typing
  src/types/evented.d.ts
  src/types/shepherd.d.ts
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: enhancement

#469 Make cancel link more accessible
  src/js/components/shepherd-content/shepherd-header/index.jsx
  src/js/components/shepherd-content/shepherd-header/styles.js
  test/unit/components/shepherd-header.spec.js
Labels: enhancement

#471 Remove shepherdElementWidth option
  demo/assets/img/intro-step.png
  demo/js/welcome.js
  demo/sheep.svg
  docs-src/tutorials/03-styling.md
  src/js/styles/generateStyles.js
  src/js/styles/variables.js
  src/js/utils/general.js
Labels: enhancement
