Repository shipshapecode/shepherd, pull requests merged in 2019-06, with the labels that each got.

#390 Fix modal padding test failures, add tests, docs
  src/js/modal.js
  src/js/step.js
  src/js/utils/modal.js
  test/unit/utils/modal.spec.js
Labels: enhancement

#395 Tippy 4.3.4, bump deps, fix lint
  package.json
  src/js/modal.js
  yarn.lock
Labels: enhancement

#402 Add scrollIntoView options and polyfill
  docs/welcome/index.html
  docs/welcome/js/welcome.js
  package.json
  src/js/step.js
  yarn.lock
Labels: enhancement

#360 Add TypeScript definitions
  package.json
  src/types/evented.d.ts
  src/types/shepherd.d.ts
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: enhancement

#407 Support close with ESC, focus tooltip on `show`
  src/js/step.js
  src/scss/_base.scss
  test/cypress/integration/a11y.spec.js
  test/unit/step.spec.js
Labels: a11y, enhancement

#409 Remove ul, li button wrapper
  docs/welcome/css/welcome.css
  src/js/step.js
  src/scss/_base.scss
  src/scss/mixins/_shepherd-button.scss
  test/dummy/css/welcome.css
  test/unit/step.spec.js
Labels: a11y, breaking, enhancement

#410 Arrow nav
  src/js/step.js
  test/cypress/integration/a11y.spec.js
  test/cypress/utils/default-steps.js
Labels: a11y, enhancement

#408 Add focus trap, to disallow tabbing outside the modal
  cypress.json
  package.json
  src/js/step.js
  test/cypress/integration/a11y.spec.js
  test/cypress/plugins/index.js
  test/cypress/support/commands.js
  test/cypress/support/index.js
  test/cypress/utils/default-steps.js
  test/unit/step.spec.js
  yarn.lock
Labels: a11y, enhancement

#411 Add aria-describedby and aria-labeledby
  src/js/step.js
  test/unit/step.spec.js
Labels: a11y, enhancement

#413 Add `disableScroll` option
  docs/welcome/css/welcome.css
  docs/welcome/index.html
  docs/welcome/js/welcome.js
  package.json
  src/js/step.js
  src/js/tour.js
  test/cypress/integration/test.acceptance.js
  test/dummy/css/welcome.css
  test/dummy/index.html
  yarn.lock
Labels: enhancement

#416 Fix jumpy disableScroll
  src/js/step.js
Labels: bug

#414 Reuse existing modal overlay
  src/js/modal.js
  test/unit/modal.spec.js
Labels: bug

#418 Remove the string option for `advanceOn` in favor of object
  README.md
  index.md
  package.json
  src/js/step.js
  src/js/utils/bind.js
  src/js/utils/general.js
  test/dummy/index.html
  test/unit/step.spec.js
  test/unit/utils/general.spec.js
  yarn.lock
Labels: breaking

#417 Remove string option for `attachTo` in favor of object
  README.md
  docs/welcome/index.html
  docs/welcome/js/welcome.js
  index.md
  src/eager/installHelper.js
  src/js/step.js
  src/js/utils/general.js
  test/cypress/integration/modal.spec.js
  test/cypress/utils/default-steps.js
  test/dummy/index.html
  test/unit/step.spec.js
  test/unit/utils/cleanup.spec.js
  test/unit/utils/dom.spec.js
  test/unit/utils/general.spec.js
Labels: breaking

#419 Remove remaining lodash, IE 11+
  .browserslistrc
  README.md
  index.md
  package.json
  src/js/modal.js
  src/js/step.js
  src/js/tour.js
  src/js/utils/general.js
  src/js/utils/type-check.js
  test/unit/utils/general.spec.js
  yarn.lock
Labels: breaking, enhancement
