Repository shipshapecode/shepherd, pull requests merged in 2019-08, with the labels that each got.

#475 fix applying tippyOptions
  src/js/utils/general.js
Labels: bug

#477 fix cancel link color for when the header has dark background
  src/js/components/shepherd-content/shepherd-header/styles.js
Labels: bug

#476 fix content border radius
  src/js/components/shepherd-content/styles.js
Labels: bug

#479 Return focus after closing the tour
  src/js/tour.jsx
Labels: a11y, enhancement

#482 Fix some TypeScript issues
  src/types/shepherd.d.ts
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: enhancement

#484 Fix some types and docs
  src/js/tour.jsx
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: enhancement

#485 Add addSteps method and allow passing steps to tour constructor
  demo/js/welcome.js
  docs-src/tutorials/02-usage.md
  src/js/components/shepherd-content/shepherd-footer/index.jsx
  src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.jsx
  src/js/step.jsx
  src/js/tour.jsx
  src/types/step.d.ts
  src/types/tour.d.ts
  test/cypress/integration/modal.spec.js
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/default-steps.js
  test/cypress/utils/setup-tour.js
  yarn.lock
Labels: enhancement

#488 Use objectAssignDeep to deeply merge tippyOptions
  demo/js/welcome.js
  package.json
  rollup.config.js
  src/js/utils/general.js
  yarn.lock
Labels: bug

#493 Support passing elements for text
  demo/js/welcome.js
  src/js/components/shepherd-content/shepherd-text/index.jsx
Labels: bug

#494 Fix for the wrong type definition of StepOptions.scrollTo
  src/types/step.d.ts
Labels: enhancement

#496 Fade in modal overlay
  src/js/components/shepherd-modal/index.jsx
  src/js/components/shepherd-modal/styles.js
  src/js/styles/generateStyles.js
  test/cypress/integration/modal.spec.js
Labels: enhancement

#506 Remove Shepherd.Evented
  docs-src/tutorials/02-usage.md
  src/js/shepherd.js
  yarn.lock
Labels: breaking

#507 Move activeTour to namespace
  src/types/shepherd.d.ts
Labels: enhancement

#508 Add keyboardNav and exitOnEsc options
  docs-src/tutorials/02-usage.md
  src/js/components/shepherd-element/index.jsx
  src/js/tour.jsx
  src/types/tour.d.ts
  test/unit/components/shepherd-element.spec.js
Labels: enhancement

#509 Remove link styles
  demo/css/welcome.css
  src/js/components/shepherd-content/shepherd-text/styles.js
Labels: breaking

#512 Add overlayOpacity to styleVariables options
  docs-src/tutorials/03-styling.md
  src/js/components/shepherd-modal/styles.js
  src/js/styles/generateStyles.js
  src/js/styles/variables.js
Labels: enhancement

#513 Use currentTarget for advanceOn
  src/js/utils/bind.js
Labels: bug

#514 Use requestAnimationFrame to position modal opening
  src/js/components/shepherd-modal/index.jsx
  src/js/utils/general.js
Labels: enhancement

#516 Remove object-assign-deep, refactor setting popper options
  .eslintrc.js
  package.json
  rollup.config.js
  src/js/utils/general.js
  src/js/utils/tippy-popper-options.js
  test/unit/utils/bind.spec.js
  test/unit/utils/tippy-popper-options.spec.js
  yarn.lock
Labels: enhancement

#518 showCancelLink -> cancelIcon
  demo/index.html
  demo/js/welcome.js
  docs-src/tutorials/02-usage.md
  src/js/components/shepherd-content/shepherd-header/index.jsx
  src/js/components/shepherd-content/shepherd-header/styles.js
  src/js/step.jsx
  src/js/styles/generateStyles.js
  src/types/step.d.ts
  test/cypress/integration/test.acceptance.js
  test/cypress/utils/setup-tour.js
  test/unit/components/shepherd-header.spec.js
Labels: breaking

#519 Remove style vendor prefixing
  src/js/styles/nano.js
Labels: breaking

#522 Add disableScroll to types
  src/types/tour.d.ts
Labels: enhancement

#523 Tie modal z-index to shepherdElementZIndex
  src/js/components/shepherd-modal/styles.js
Labels: enhancement

#526 Add includeStyles option
  docs-src/tutorials/02-usage.md
  src/js/components/shepherd-content/shepherd-footer/shepherd-button/styles.js
  src/js/components/shepherd-content/shepherd-footer/styles.js
  src/js/components/shepherd-content/shepherd-header/styles.js
  src/js/components/shepherd-content/shepherd-text/styles.js
  src/js/components/shepherd-content/styles.js
  src/js/styles/generateStyles.js
  src/js/tour.jsx
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: enhancement
