Repository shipshapecode/shepherd, pull requests merged in 2020-05, with the labels that each got.

#908 🐛 Fix centered sizing and add max height defaults for text
  src/js/components/shepherd-element.svelte
  src/js/components/shepherd-text.svelte
Labels: enhancement

#959 Add deepmerge for deep clone functionality
  package.json
  src/js/step.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
  yarn.lock
Labels: bug

#982 Officially drop IE 11 and remove from browserslist
  .browserslistrc
  landing/css/welcome.css
Labels: breaking
