Repository shipshapecode/shepherd, pull requests merged in 2020-04, with the labels that each got.

#879 Prevent header from rendering when empty
  src/js/components/shepherd-content.svelte
  test/unit/components/shepherd-content.spec.js
Labels: enhancement

#920 Fix defaultStepOptions.popperOptions issues
  .prettierrc.js
  src/js/utils/general.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
Labels: bug

#922 Add offset to cookbook
  docs-src/tutorials/04-cookbook.md
Labels: documentation

#935 cookbook - progress bar code snippet fix to show in all steps
  docs-src/tutorials/04-cookbook.md
Labels: documentation
