Repository shipshapecode/shepherd, pull requests merged in 2020-07, with the labels that each got.

#1026 Add Edge 18 to browserslist
  .browserslistrc
Labels: enhancement

#1039 Use isElement fot svg scrollIntoView support
  src/js/components/shepherd-text.svelte
  src/js/step.js
  src/js/tour.js
  src/js/utils/type-check.js
Labels: bug

#1044 add Step.id to typings, fix tour.getById() typing
  src/types/step.d.ts
  src/types/tour.d.ts
Labels: internal
