Repository shipshapecode/shepherd, pull requests merged in 2022-11, with the labels that each got.

#2129 Replace references to popperjs
  docs-src/tutorials/02-usage.md
  docs-src/tutorials/04-cookbook.md
  landing/js/welcome.js
  src/js/step.js
  src/types/step.d.ts
  test/cypress/utils/default-steps.js
Labels: documentation

#2157 Remove firefox tests
  .github/workflows/test.yml
  package.json
Labels: internal

#2137 Exporting StepOptionsButton type to be able to add tour steps buttons dynamically with type checking
  src/types/step.d.ts
Labels: enhancement
