Repository shipshapecode/shepherd, pull requests merged in 2024-09, with the labels that each got.

#2966 ⬆ Update Astro to v14.15
  docs-src/astro.config.mjs
  docs-src/package.json
  pnpm-lock.yaml
Labels: dependencies, internal

#2967 📝 Add docs for analytics and react usage
  docs-src/astro.config.mjs
  docs-src/src/assets/houston.webp
  docs-src/src/assets/pro-integrations.png
  docs-src/src/content/docs/example.mdx
  docs-src/src/content/docs/guides/analytics.mdx
  docs-src/src/content/docs/recipes/react.md
  docs-src/src/content/docs/reference/docker.md
Labels: documentation, internal

#2968 Landing: 🔥 Remove and upgrade dependencies
  .github/workflows/landing-deploy.yml
  landing/Dockerfile
  landing/astro.config.mjs
  landing/package.json
  landing/src/components/Header.astro
  landing/src/pages/[...slug].astro
  landing/src/pages/blog/[...slug].astro
  landing/src/pages/blog/index.astro
  landing/src/pages/demo.astro
  landing/src/pages/index.astro
  landing/src/pages/pricing.astro
  landing/src/storyblok/AllArticles.astro
  landing/src/storyblok/Article.astro
  landing/tsconfig.json
  pnpm-lock.yaml
Labels: internal

#2969 📄 Update license for commercial use cases
  LICENSE
Labels: internal

#2973 📝 Update documentation for correct url
  README.md
  landing/astro.config.mjs
  landing/src/layouts/MainPage.astro
  landing/src/pages/index.astro
  packages/react/README.md
  shepherd.js/README.md
  shepherd.js/package.json
Labels: documentation, internal

#2975 🐛 Landing: Remove import string from frontmatter
  landing/src/pages/index.astro
Labels: internal

#2976 Update license to AGPL-3.0
  .prettierrc.js
  .tool-versions
  LICENSE.md
  package.json
  shepherd.js/package.json
Labels: breaking

#2980 🐛 Fix event timing issue and add button for demo start
  docs-src/src/content/docs/recipes/cookbook.md
  landing/src/components/Header.astro
  landing/src/pages/index.astro
  shepherd.js/src/tour.ts
Labels: bug

#2979 Fix handler type for Evented.off()
  shepherd.js/src/evented.ts
Labels: bug

#2981 🔥 Pro: Remove deprecated pro package
  packages/pro-js/CHANGELOG.md
  packages/pro-js/README.md
  packages/pro-js/package.json
  packages/pro-js/src/DataRequest.ts
  packages/pro-js/src/index.ts
  packages/pro-js/src/utils/context.ts
  packages/pro-js/test/datarequest.test.ts
  packages/pro-js/test/index.test.ts
  packages/pro-js/tsconfig.json
  packages/pro-js/vite.config.ts
  packages/pro-js/vitest.config.ts
Labels: internal

#2988 🐛 Landing: Fix checkout issue with correct PAT
  landing/astro.config.mjs
  landing/package.json
  landing/src/actions/index.ts
  landing/src/pages/pricing.astro
  packages/react/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#2974 Update some various styles
  .prettierrc.js
  .tool-versions
  landing/src/pages/index.astro
  landing/src/pages/pricing.astro
  package.json
  pnpm-lock.yaml
Labels: documentation
