Repository shipshapecode/shepherd, pull requests merged in 2024-10, with the labels that each got.

#2982 ✨ Update shepherd element to use html dialog
  landing/src/styles/shepherd.css
  shepherd.js/src/components/shepherd-content.svelte
  shepherd.js/src/components/shepherd-element.svelte
  test/cypress/integration/a11y.cy.js
Labels: enhancement

#3005 🐛 Fix issue where passed in custom middleware is overridden
  shepherd.js/src/utils/floating-ui.ts
  test/unit/utils/general.spec.js
Labels: bug

#3011 Fix options type for `options.floatingUIOptions`
  shepherd.js/src/step.ts
  shepherd.js/src/utils/floating-ui.ts
Labels: bug

#3025 Fix loading on button, add link to root page on logo
  landing/src/components/Header.astro
  landing/src/pages/index.astro
  landing/src/pages/pricing.astro
Labels: documentation

#2995 Implement multiple element highlighting feature
  docs-src/src/content/docs/recipes/cookbook.md
  landing/src/components/Header.astro
  landing/src/pages/index.astro
  shepherd.js/src/components/shepherd-modal.svelte
  shepherd.js/src/step.ts
  shepherd.js/src/utils/cleanup.ts
  shepherd.js/src/utils/general.ts
  shepherd.js/src/utils/overlay-path.ts
  test/unit/components/shepherd-modal.spec.js
  test/unit/utils/cleanup.spec.js
  test/unit/utils/general.spec.js
Labels: enhancement

#3009 Add 'auto' as placement option
  docs-src/src/content/docs/guides/usage.md
  shepherd.js/src/step.ts
  shepherd.js/src/utils/floating-ui.ts
  test/unit/tour.spec.js
Labels: enhancement, hacktoberfest
