Repository shipshapecode/shepherd, pull requests merged in 2024-04, with the labels that each got.

#2670 Remove NoOp type usage
  landing/src/layouts/MainPage.astro
  shepherd.js/src/shepherd.ts
  shepherd.js/src/tour.ts
Labels: internal

#2682 Simplify rollup config
  pnpm-lock.yaml
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
Labels: bug

#2683 Update to Svelte 4, run ESM in tests
  .eslintrc.js
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
  shepherd.js/.eslintrc.js
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  shepherd.js/src/components/shepherd-title.svelte
  test/cypress/package.json
  test/unit/babel.config.cjs
  test/unit/components/shepherd-element.spec.js
  test/unit/components/shepherd-header.spec.js
  test/unit/components/shepherd-modal.spec.js
  test/unit/evented.spec.js
  test/unit/jest.config.js
  test/unit/package.json
  test/unit/pro.spec.js
  test/unit/setupTests.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
  test/unit/utils/bind.spec.js
  test/unit/utils/datarequest.spec.js
  test/unit/utils/general.spec.js
Labels: breaking

#2684 Use IndexedDB to store tour data
  landing/src/layouts/MainPage.astro
  pnpm-lock.yaml
  shepherd.js/package.json
  shepherd.js/src/tour.ts
  shepherd.js/src/utils/datarequest.ts
  test/unit/pro.spec.js
Labels: enhancement

#2686 Add tests for `Shepherd.isTourEnabled`
  pnpm-lock.yaml
  shepherd.js/src/utils/datarequest.ts
  test/unit/jest.config.js
  test/unit/package.json
  test/unit/pro.spec.js
  test/unit/setupTests.js
  test/unit/utils/datarequest.spec.js
Labels: internal

#2713 App: ⬆ Update Redwood to v7.3.2
  .gitignore
  app/.yarn/install-state.gz
  app/api/package.json
  app/package.json
  app/web/package.json
  app/yarn.lock
Labels: internal

#2715 Landing: 💬 Add codepen as OSS user
  landing/public/users/google.svg
  landing/src/layouts/MainPage.astro
Labels: internal

#2716 App: ✨ Add description field to demo request form
  app/api/src/graphql/emails.sdl.ts
  app/api/src/mail/DemoRequest/DemoRequest.tsx
  app/api/src/services/emails/emails.ts
  app/api/types/graphql.d.ts
  app/web/src/components/DemoDialog/DemoDialog.tsx
Labels: internal

#2724 App: 🐛 Fix some TS errors from emails fix and prerender landing page
  app/api/src/services/emails/emails.ts
  app/web/src/App.tsx
  app/web/src/Routes.tsx
  app/web/src/components/DemoDialog/DemoDialog.tsx
  app/web/src/pages/SignUpContactPage/SignUpContactPage.tsx
Labels: internal

#2707 React: ✨ Adding improved provider for v5 release
  packages/react/package.json
  packages/react/src/index.tsx
  packages/react/test/index.test.tsx
  packages/react/tsconfig.json
Labels: breaking

#2727 App: 🐛 Update before show of tour to wait for element to render
  app/web/src/layouts/AppBaseLayout/AppBaseLayout.tsx
Labels: internal

#2734 Blog: 📝 Add alpha launch blog post
  landing/src/content/blog/alpha-launch-pro.md
  landing/src/images/blog/npm-trends.png
  landing/src/images/blog/star-history.png
Labels: internal

#2736 Blog: 🐛 Add sharp for pnpm based md image processing
  landing/package.json
  landing/src/images/blog/star-history.png
  pnpm-lock.yaml
Labels: internal

#2732 Update README.md
  README.md
Labels: internal

#2737 App: 💄 Update main landing page
  app/web/config/tailwind.config.js
  app/web/public/img/screen-journeys.png
  app/web/public/img/ship-shape-logo.png
  app/web/public/img/ship-shape-logo.svg
  app/web/public/users/browserless.svg
  app/web/public/users/codepen.svg
  app/web/src/components/Footer/index.tsx
  app/web/src/index.html
  app/web/src/layouts/AuthLayout/AuthLayout.tsx
  app/web/src/layouts/SignupLandingLayout/SignupLandingLayout.tsx
  app/web/src/pages/SignUpContactPage/SignUpContactPage.tsx
Labels: internal

#2717 Docs: 📝 Move docs generator to Starlight and typedoc
  .github/workflows/docs-deploy.yml
  .github/workflows/publish-github-pages.yml
  .jsdoc.js
  app/docker-compose.dev.yml
  app/docker-compose.prod.yml
  app/docker-compose.yml
  app/web/src/components/Footer/index.tsx
  app/web/src/components/Navigation/UserMenu.tsx
  docs-src/.dockerignore
  docs-src/.gitignore
  docs-src/.vscode/extensions.json
  docs-src/.vscode/launch.json
  docs-src/Dockerfile
  docs-src/README.md
  docs-src/astro.config.mjs
  docs-src/fly.toml
  docs-src/package.json
  docs-src/public/favicon.ico
  docs-src/public/favicon.svg
  docs-src/src/assets/Shepherd-Lamb.svg
  docs-src/src/assets/houston.webp
  docs-src/src/content/config.ts
  docs-src/src/content/docs/api/README.md
  docs-src/src/content/docs/example.mdx
  docs-src/src/content/docs/guides/install.mdx
  docs-src/src/content/docs/guides/setup.md
  docs-src/src/content/docs/guides/styling.md
  docs-src/src/content/docs/guides/usage.md
  docs-src/src/content/docs/recipes/cookbook.md
  docs-src/src/content/docs/reference/docker.md
  docs-src/src/env.d.ts
  docs-src/src/pages/index.astro
  docs-src/tailwind.config.mjs
  docs-src/tsconfig.json
  docs-src/tutorials/01-install.md
  docs-src/tutorials/config.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  shepherd.js/.npmignore
  shepherd.js/package.json
  shepherd.js/tsconfig.json
Labels: documentation
