Repository shipshapecode/shepherd, pull requests merged in 2024-06, with the labels that each got.

#2853 fix: reconfigure CSS bundling
  pnpm-lock.yaml
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  test/cypress/examples/css/no-css-import.html
  test/cypress/examples/css/with-css-import.html
  test/cypress/integration/css.cy.js
Labels: bug

#2838 tweak: prevents header links overflow in small screens
  landing/src/components/Header.astro
Labels: review in progress, internal

#2870 ✨ Add new package specific to Pro features
  docs-src/package.json
  package.json
  packages/pro-js/CHANGELOG.md
  packages/pro-js/README.md
  packages/pro-js/package.json
  packages/pro-js/src/DataRequest.ts
  packages/pro-js/src/index.ts
  packages/pro-js/src/utils/context.ts
  packages/pro-js/test/datarequest.test.ts
  packages/pro-js/test/index.test.ts
  packages/pro-js/tsconfig.json
  packages/pro-js/vite.config.ts
  packages/pro-js/vitest.config.ts
  packages/react/package.json
  packages/react/src/index.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
  shepherd.js/package.json
  shepherd.js/src/shepherd.ts
  shepherd.js/src/tour.ts
  test/cypress/package.json
  test/unit/package.json
  test/unit/pro.spec.js
  test/unit/setupTests.js
  test/unit/utils/datarequest.spec.js
Labels: breaking

#2877 👷 Add correct token to publish all packages
  .github/workflows/publish.yml
  landing/src/pages/demo.astro
  package.json
Labels: internal

#2878 👷 Add prepack script to pro-js
  packages/pro-js/package.json
Labels: bug

#2880 📝 Add updated documentation for pro package and updated CDN links
  README.md
  docs-src/astro.config.mjs
  docs-src/src/content/docs/guides/install.mdx
  docs-src/src/content/docs/guides/setup.mdx
  landing/src/pages/demo.astro
Labels: documentation

#2883 🐛 Fix bug where events fail to fire due to naming
  packages/pro-js/src/index.ts
Labels: bug

#2885 🐛 Fix missing tour active check
  packages/pro-js/package.json
  packages/pro-js/src/index.ts
  packages/react/package.json
Labels: bug

#2887 🐛 Fix issue with object merge to push events to pro app
  packages/pro-js/src/index.ts
Labels: bug

#2895 ✨ Add reading for isAutoStart value sent from app
  packages/pro-js/package.json
  packages/pro-js/src/DataRequest.ts
  packages/pro-js/src/index.ts
  packages/pro-js/test/datarequest.test.ts
  packages/pro-js/test/index.test.ts
  packages/pro-js/vitest.config.ts
  pnpm-lock.yaml
Labels: enhancement

#2898 👷 Fix changelog error on merges
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  stderr.log
Labels: internal

#2900 🐛 Add small padding to arrow if edge alignment is used
  shepherd.js/src/utils/floating-ui.ts
Labels: bug
