Repository shipshapecode/shepherd, pull requests merged in 2024-03, with the labels that each got.

#2607 Switch from yarn to pnpm, initial monorepo setup
  .github/workflows/publish-github-pages.yml
  .github/workflows/test.yml
  .npmignore
  .release-it.js
  .yarn/releases/yarn-4.1.0.cjs
  .yarnrc.yml
  CONTRIBUTING.md
  RELEASE.md
  docs-src/tutorials/01-install.md
  landing/package.json
  landing/yarn.lock
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  yarn.lock
Labels: internal

#2601 👷‍ Add typescript with minimal setup
  jest.config.js
  package.json
  pnpm-lock.yaml
  rollup.config.js
  tsconfig.json
Labels: internal

#2608 Fix cypress tests
  .github/workflows/test.yml
Labels: internal

#2610 Move files from src/js to src, convert to TS
  .github/workflows/test.yml
  .jsdoc.js
  .release-it.js
  babel.config.js
  docs-src/tutorials/01-install.md
  docs-src/tutorials/02-usage.md
  jest.config.js
  landing/src/layouts/MainPage.astro
  package.json
  pnpm-lock.yaml
  rollup.config.js
  src/components/shepherd-button.svelte
  src/components/shepherd-cancel-icon.svelte
  src/components/shepherd-content.svelte
  src/components/shepherd-element.svelte
  src/components/shepherd-footer.svelte
  src/components/shepherd-header.svelte
  src/components/shepherd-modal.svelte
  src/components/shepherd-text.svelte
  src/components/shepherd-title.svelte
  src/evented.ts
  src/js/utils/overlay-path.js
  src/js/utils/type-check.js
  src/shepherd.ts
  src/step.ts
  src/tour.ts
  src/types/evented.d.ts
  src/types/shepherd.d.ts
  src/types/step.d.ts
  src/types/tour.d.ts
  src/utils/auto-bind.ts
  src/utils/bind.ts
  src/utils/cleanup.ts
  src/utils/floating-ui.ts
  src/utils/general.ts
  src/utils/overlay-path.ts
  src/utils/type-check.ts
  test/dummy/index.html
  test/examples/destroying-elements.html
  test/unit/components/shepherd-button.spec.js
  test/unit/components/shepherd-content.spec.js
  test/unit/components/shepherd-element.spec.js
  test/unit/components/shepherd-footer.spec.js
  test/unit/components/shepherd-header.spec.js
  test/unit/components/shepherd-modal.spec.js
  test/unit/components/shepherd-text.spec.js
  test/unit/components/shepherd-title.spec.js
  test/unit/evented.spec.js
  test/unit/server.spec.js
  test/unit/step.spec.js
  test/unit/tour.spec.js
  test/unit/utils/bind.spec.js
  test/unit/utils/cleanup.spec.js
  test/unit/utils/general.spec.js
  tsconfig.json
Labels: breaking

#2616 Update rollup packages
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: dependencies

#2615 Adjust exports and rollup config
  .npmignore
  landing/package.json
  landing/src/layouts/MainPage.astro
  package.json
  pnpm-lock.yaml
  rollup.config.mjs
  tsconfig.json
Labels: internal

#2620 ✨ Add Pro events sharing
  src/tour.ts
  src/utils/datarequest.ts
  test/unit/pro.spec.js
  test/unit/utils/datarequest.spec.js
  tsconfig.json
Labels: enhancement

#2621 Add release-plan
  .eslintrc.js
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#2626 Convert to ESM
  docs-src/tutorials/01-install.md
  docs-src/tutorials/02-usage.md
  landing/src/layouts/MainPage.astro
  package.json
  pnpm-lock.yaml
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  shepherd.js/src/step.ts
  shepherd.js/src/utils/floating-ui.ts
  test/cypress/.gitignore
  test/cypress/cypress.config.js
  test/cypress/dummy/index.html
  test/cypress/examples/destroying-elements.html
  test/cypress/package.json
  test/cypress/plugins/index.js
  test/unit/package.json
Labels: breaking

#2632 Move Step and Tour assignment
  shepherd.js/src/shepherd.ts
  shepherd.js/src/tour.ts
Labels: enhancement

#2631 Add EventOptions interface, tweak data format
  shepherd.js/src/shepherd.ts
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
  shepherd.js/src/utils/general.ts
Labels: enhancement

#2613 Add TS support for JSDoc
  .github/workflows/publish-github-pages.yml
  .jsdoc.js
  landing/astro.config.mjs
  landing/package.json
  landing/src/layouts/Base.astro
  landing/src/layouts/BlogPost.astro
  landing/src/layouts/MainPage.astro
  landing/src/pages/blog/[...slug].astro
  landing/src/pages/blog/index.astro
  landing/src/pages/demo.astro
  landing/src/pages/index.astro
  landing/src/pages/pricing.astro
  landing/tsconfig.json
  package.json
  pnpm-lock.yaml
  shepherd.js/src/components/shepherd-button.svelte
  shepherd.js/src/components/shepherd-content.svelte
  shepherd.js/src/components/shepherd-element.svelte
  shepherd.js/src/components/shepherd-modal.svelte
  shepherd.js/src/components/shepherd-text.svelte
  shepherd.js/src/components/shepherd-title.svelte
  shepherd.js/src/evented.ts
  shepherd.js/src/shepherd.ts
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
  shepherd.js/src/utils/bind.ts
  shepherd.js/src/utils/cleanup.ts
  shepherd.js/src/utils/floating-ui.ts
  shepherd.js/src/utils/general.ts
  shepherd.js/tsconfig.json
Labels: documentation

#2646 Fix docs build
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
Labels: documentation

#2647 Remove webcomponents polyfill
  landing/src/components/Footer.astro
Labels: documentation

#2659 🐛 Update user ID ref to be direct from localstorage
  shepherd.js/src/tour.ts
Labels: bug

#2662 Document release process
  LICENSE.md
  README.md
  RELEASE.md
Labels: documentation

#2664 Add extra properties bucket to send to Shepherd Pro
  shepherd.js/src/tour.ts
  shepherd.js/src/utils/context.ts
  shepherd.js/src/utils/datarequest.ts
  test/unit/pro.spec.js
  test/unit/utils/datarequest.spec.js
Labels: enhancement

#2665 Add async/await for ShepherdPro init
  shepherd.js/src/tour.ts
  test/unit/pro.spec.js
Labels: bug

#2667 Move `properties` under the `data` object
  shepherd.js/src/utils/datarequest.ts
  test/unit/utils/datarequest.spec.js
Labels: enhancement

#2649 ✨ Add initial React package from SDK
  .github/workflows/test.yml
  package.json
  packages/react/.gitignore
  packages/react/CHANGELOG.md
  packages/react/README.md
  packages/react/package.json
  packages/react/src/index.tsx
  packages/react/test/index.test.tsx
  packages/react/test/setup.ts
  packages/react/tsconfig.json
  packages/react/vite.config.ts
  packages/react/vitest.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/cypress/package.json
Labels: enhancement
