Repository shipshapecode/shepherd, pull requests merged in 2024-07, with the labels that each got.

#2882 ➖ Remove release-it package and configs
  RELEASE.md
  package.json
  packages/react/package.json
  pnpm-lock.yaml
Labels: internal

#2911 ✨ Pro: Add functions to pro for taking config from API
  packages/pro-js/src/DataRequest.ts
  packages/pro-js/src/index.ts
  packages/pro-js/test/datarequest.test.ts
  packages/pro-js/test/index.test.ts
Labels: enhancement

#2912 ⬆ Update of Astro to v4.12 and related deps upgrades
  docs-src/package.json
  docs-src/src/content/docs/api/README.md
  landing/package.json
  pnpm-lock.yaml
Labels: dependencies

#2920 👷 Fix package for correct release plan build ordering
  package.json
  packages/pro-js/package.json
  packages/react/package.json
  pnpm-workspace.yaml
Labels: bug

#2922 👷 Add publish config and scarf paackage
  packages/pro-js/package.json
  packages/react/package.json
  pnpm-lock.yaml
  shepherd.js/package.json
Labels: dependencies, internal

#2924 Update publish.yml to have node-registry-url
  .github/workflows/publish.yml
Labels: internal

#2928 📝 Docs updates for pro beta setup/usage
  docs-src/src/content/docs/guides/install.mdx
  docs-src/src/content/docs/guides/setup.mdx
Labels: documentation, internal

#2929 ➖ React: Remove extra pro specific setup
  packages/pro-js/package.json
  packages/react/package.json
  packages/react/src/index.tsx
  packages/react/test/index.test.tsx
  pnpm-lock.yaml
Labels: enhancement
