Repository shipshapecode/shepherd, pull requests merged in 2024-05, with the labels that each got.

#2765 Revert CI changes
  .github/workflows/test.yml
  pnpm-lock.yaml
  shepherd.js/src/components/shepherd-button.svelte
  test/unit/package.json
Labels: internal

#2768 Docs: 📝 Add page for pro analytics
  docs-src/astro.config.mjs
  docs-src/src/assets/pro-integrations.png
  docs-src/src/content/docs/guides/analytics.mdx
Labels: documentation

#2775 Docs: ➕ Add posthog for analytics to both docs and landing
  docs-src/astro.config.mjs
  docs-src/src/components/HeadWithPosthog.astro
  docs-src/src/components/Posthog.astro
  landing/astro.config.mjs
  landing/package.json
  landing/src/components/BaseHead.astro
  landing/src/components/Header.astro
  landing/src/components/Posthog.astro
  pnpm-lock.yaml
Labels: internal

#2776 App: ✨ Add initial Chargebee integration, under feature flag
  app/.yarn/install-state.gz
  app/api/db/migrations/20240426230316_subscriptions_start/migration.sql
  app/api/db/migrations/20240430175837_fix_subs/migration.sql
  app/api/db/migrations/20240430180434_fix_sub_user/migration.sql
  app/api/db/schema.prisma
  app/api/package.json
  app/api/src/functions/auth.ts
  app/api/src/graphql/subscriptions.sdl.ts
  app/api/src/services/subscriptions/subscriptions.scenarios.ts
  app/api/src/services/subscriptions/subscriptions.test.ts
  app/api/src/services/subscriptions/subscriptions.ts
  app/api/src/services/users/users.ts
  app/api/types/graphql.d.ts
  app/redwood.toml
  app/web/package.json
  app/web/src/Routes.tsx
  app/web/src/components/Navigation/UnAuthNav.tsx
  app/web/src/components/SubscriptionFeature/SubscriptionFeature.tsx
  app/web/src/index.html
  app/web/src/layouts/AuthLayout/AuthLayout.tsx
  app/web/src/layouts/SignupLandingLayout/SignupLandingLayout.tsx
  app/web/src/pages/AccountPage/AccountCards/ChangeEmailCard.tsx
  app/web/src/pages/AccountPage/AccountCards/ChangePasswordCard.tsx
  app/web/src/pages/AccountPage/AccountCards/DeleteAccountCard.tsx
  app/web/src/pages/AccountPage/AccountPage.tsx
  app/web/src/pages/HomePage/HomePage.tsx
  app/web/src/pages/PricingPage/PricingPage.stories.tsx
  app/web/src/pages/PricingPage/PricingPage.test.tsx
  app/web/src/pages/PricingPage/PricingPage.tsx
  app/web/src/pages/SignUpContactPage/SignUpContactPage.tsx
  app/web/src/pages/SignupPage/SignupPage.tsx
  app/web/types/graphql.d.ts
  app/yarn.lock
Labels: internal

#2786 App: 🚑️ Fix to disable post for checkout url
  app/api/src/functions/auth.ts
Labels: internal

#2789 Add prepack scripts
  packages/react/package.json
  shepherd.js/package.json
Labels: bug

#2788 App: 🗃️ Add migration to give all users a subscription
  app/api/db/migrations/20240503234707_subscription_default/migration.sql
  app/api/db/schema.prisma
Labels: internal

#2793 🐛 Add fix for modal reshow from 2436
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
Labels: bug

#2805 🐛 Fixes import issues reported in 2785
  landing/src/layouts/MainPage.astro
  pnpm-lock.yaml
  shepherd.js/.eslintignore
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  shepherd.js/scripts/postprocess.js
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
  shepherd.js/tsconfig.json
Labels: bug

#2809 React: 👷 Update tsc target to match lowest compatibility
  app/.yarn/install-state.gz
  app/yarn.lock
  packages/react/package.json
  packages/react/src/index.tsx
  packages/react/tsconfig.json
  pnpm-lock.yaml
Labels: bug

#2812 Landing: 👷 Add fly.io deployment
  .github/workflows/landing-deploy.yml
  .github/workflows/publish-github-pages.yml
  landing/Dockerfile
  landing/astro.config.mjs
  landing/fly.toml
  landing/package.json
  landing/src/components/BaseHead.astro
  package.json
  pnpm-lock.yaml
  shepherd.js/README.md
  shepherd.js/package.json
Labels: internal

#2821 Landing: 🐛 Fix config for canonicalURL
  landing/src/components/BaseHead.astro
Labels: bug

#2822 App: 🐛 Fix IP address check for webhook
  app/api/src/functions/subscriptions/subscriptions.test.ts
  app/api/src/functions/subscriptions/subscriptions.ts
Labels: internal

#2826 Landing: 🐛 Update Dockerfile to build JS lib before copy
  landing/Dockerfile
  landing/astro.config.mjs
Labels: internal

#2827 Landing: 🐛 Update action to build js lib before docker copys it
  .github/workflows/landing-deploy.yml
  landing/Dockerfile
Labels: internal

#2828 React: 🐛 Fix init to be optional
  packages/react/README.md
  packages/react/src/index.tsx
Labels: bug

#2820 Fix TS issues, more correctly ship CJS and ESM
  docs-src/src/content/docs/guides/install.mdx
  landing/src/layouts/MainPage.astro
  pnpm-lock.yaml
  shepherd.js/.eslintignore
  shepherd.js/.eslintrc.cjs
  shepherd.js/.npmignore
  shepherd.js/babel.config.cjs
  shepherd.js/errors.json
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  shepherd.js/scripts/postprocess.js
  shepherd.js/src/evented.ts
  shepherd.js/src/step.ts
  shepherd.js/src/tour.ts
  shepherd.js/svelte.config.js
  shepherd.js/tsconfig.json
  test/cypress/dummy/index.html
  test/cypress/examples/destroying-elements.html
  test/cypress/package.json
Labels: bug

#2835 Landing: ➕ Update node version for deployment action
  .github/workflows/landing-deploy.yml
  shepherd.js/README.md
Labels: internal

#2836 App: ⬆ Upgrade RW version to v7.6
  app/.yarn/install-state.gz
  app/api/package.json
  app/package.json
  app/web/package.json
  app/yarn.lock
Labels: internal

#2839 Export CSS and just create one file
  docs-src/package.json
  docs-src/src/content/docs/guides/install.mdx
  shepherd.js/package.json
  shepherd.js/rollup.config.mjs
  test/cypress/dummy/index.html
  test/cypress/examples/destroying-elements.html
Labels: bug

#2844 App: ⬆ Upgrade Shepherd lib in the app to v5
  app/.yarn/install-state.gz
  app/api/src/functions/state/state.ts
  app/web/package.json
  app/web/src/layouts/AppBaseLayout/AppBaseLayout.tsx
  app/web/src/pages/PricingPage/PricingPage.tsx
  app/yarn.lock
  pnpm-workspace.yaml
Labels: internal
